import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		n: 'gridPaddingLeft',
		cp: 'padding-left',
		dn: 'Grid Left padding',
		de: 'Left padding for grid.',
		sel: '.comp.compGrid._noAnchorGrid',
	},
	{
		n: 'gridPaddingRight',
		cp: 'padding-right',
		dn: 'Grid Right padding',
		de: 'Right padding for grid.',
		sel: '.comp.compGrid._noAnchorGrid',
	},
	{
		n: 'gridPaddingTop',
		cp: 'padding-top',
		dn: 'Grid Top padding',
		de: 'Top padding for grid.',
		sel: '.comp.compGrid._noAnchorGrid',
	},
	{
		n: 'gridPaddingBottom',
		cp: 'padding-bottom',
		dn: 'Grid Bottom padding',
		de: 'Bottom padding for grid.',
		sel: '.comp.compGrid._noAnchorGrid',
	},
	{
		n: 'anchoredGridPaddingLeft',
		cp: 'padding-left',
		dn: 'Grid Left padding',
		de: 'Left padding for grid.',
		sel: '.comp.compGrid ._anchorGrid',
	},
	{
		n: 'anchoredGridPaddingRight',
		cp: 'padding-right',
		dn: 'Grid Right padding',
		de: 'Right padding for grid.',
		sel: '.comp.compGrid ._anchorGrid',
	},
	{
		n: 'anchoredGridPaddingTop',
		cp: 'padding-top',
		dn: 'Grid Top padding',
		de: 'Top padding for grid.',
		sel: '.comp.compGrid ._anchorGrid',
	},
	{
		n: 'anchoredGridPaddingBottom',
		cp: 'padding-bottom',
		dn: 'Grid Bottom padding',
		de: 'Bottom padding for grid.',
		sel: '.comp.compGrid ._anchorGrid',
	},
	{
		n: 'gapBetween',
		cp: 'gap',
		dn: 'Gap between children',
		de: 'Gap between children of grid.',
		dv: '5px',
		sel: '.comp.compGrid ._anchorGrid, .comp.compGrid._noAnchorGrid',
	},
	{
		gn: 'Border',
		dn: 'Border Light',
		n: 'borderLight',
		dv: '1px solid',
		cp: 'border',
		sel: '._LIGHT',
	},
	{
		gn: 'Border',
		dn: 'Border Medium',
		n: 'borderMedium',
		dv: '3px solid',
		cp: 'border',
		sel: '._MEDIUM',
	},
	{
		gn: 'Border',
		dn: 'Border High',
		n: 'borderHigh',
		dv: '5px solid',
		cp: 'border',
		sel: '._HEAVY',
	},

	{
		gn: 'Border Radius',
		dn: 'Border Radius Straight',
		n: 'borderRadiusStraight',
		dv: '0px ',
		cp: 'border-radius',
		sel: '._STRAIGHT',
	},
	{
		gn: 'Border Radius',
		dn: 'Border Radius Round',
		n: 'borderRadiusRound',
		dv: '10px ',
		cp: 'border-radius',
		sel: '._ROUND',
	},
	{
		gn: 'Border Radius',
		dn: 'Border Radius Very Round',
		n: 'borderRadiusVeryRound',
		dv: '30px',
		cp: 'border-radius',
		sel: '._VERYROUND',
	},

	{
		gn: 'Box Shadow',
		dn: 'Box Shadow DarkLow',
		n: 'boxShadowDarkLow',
		dv: '0px 3px 10px 0px rgba(255, 255, 255, 0.10)',
		cp: 'box-shadow',
		sel: '._DARKLOW',
	},
	{
		gn: 'Box Shadow',
		dn: 'Box Shadow DarkMedium',
		n: 'boxShadowDarkMedium',
		dv: '0px 5px 20px 0px rgba(255, 255, 255, 0.20)',
		cp: 'box-shadow',
		sel: '._DARKMEDIUM',
	},
	{
		gn: 'Box Shadow',
		dn: 'Box Shadow DarkHigh',
		n: 'boxShadowDarkHigh',
		dv: '0px 5px 30px 0px rgba(255, 255, 255, 0.30)',
		cp: 'box-shadow',
		sel: '._DARKHIGH',
	},
	{
		gn: 'Box Shadow',
		dn: 'Box Shadow LightLow',
		n: 'boxShadowLightLow',
		dv: '0px 3px 10px 0px rgba(0, 0, 0, 0.10)',
		cp: 'box-shadow',
		sel: '._LIGHTLOW',
	},
	{
		gn: 'Box Shadow',
		dn: 'Box Shadow LightMedium',
		n: 'boxShadowLightMedium',
		dv: '0px 5px 20px 0px rgba(0, 0, 0, 0.20)',
		cp: 'box-shadow',
		sel: '._LIGHTMEDIUM',
	},
	{
		gn: 'Box Shadow',
		dn: 'Box Shadow LightHigh',
		n: 'boxShadowLightHigh',
		dv: '0px 5px 30px 0px rgba(0, 0, 0, 0.30)',
		cp: 'box-shadow',
		sel: '._LIGHTHIGH',
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
