import { StylePropertyDefinition } from '../../types/common';
export const styleProperties: Array<StylePropertyDefinition> = [
	{
		gn: 'Button Bar Height',
		dn: 'Button Bar Height Buttons Height',
		n: 'buttonBarHeightButtonsHeight',
		dv: '32px',
		cp: 'height',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button, .comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Background Color',
		dn: 'Button Bar Background Color Primary  Button Background',
		n: 'buttonBarBackgroundColorPrimaryButtonBackground',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._primary ._button,.comp.compButtonBar._buttonBarDesign2._primary ._button,.comp.compButtonBar._buttonBarDesign3._primary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Background Color',
		dn: 'Button Bar Background Color Secondary  Button Background',
		n: 'buttonBarBackgroundColorSecondaryButtonBackground',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._secondary ._button,.comp.compButtonBar._buttonBarDesign2._secondary ._button,.comp.compButtonBar._buttonBarDesign3._secondary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Background Color',
		dn: 'Button Bar Background Color Tertiary  Button Background',
		n: 'buttonBarBackgroundColorTertiaryButtonBackground',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._tertiary ._button,.comp.compButtonBar._buttonBarDesign2._tertiary ._button,.comp.compButtonBar._buttonBarDesign3._tertiary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Background Color',
		dn: 'Button Bar Background Color Quatranary  Button Background',
		n: 'buttonBarBackgroundColorQuatranaryButtonBackground',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._quaternary ._button, .comp.compButtonBar._buttonBarDesign2._quaternary ._button, .comp.compButtonBar._buttonBarDesign3._quaternary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Background Color',
		dn: 'Button Bar Background Color Quinary  Button Background',
		n: 'buttonBarBackgroundColorQuinaryButtonBackground',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._quinary ._button,.comp.compButtonBar._buttonBarDesign2._quinary ._button,.comp.compButtonBar._buttonBarDesign3._quinary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Hover Background Color',
		dn: 'Button Bar Hover Background Color Primary Background',
		n: 'buttonBarHoverBackgroundColorPrimaryBackground',
		dv: '<backgroundHoverColorOne>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._primary ._button:hover, .comp.compButtonBar._buttonBarDesign2._primary ._button:hover, .comp.compButtonBar._buttonBarDesign3._primary ._button:hover, .comp.compButtonBar._buttonBarDesign1._primary ._button._selected, .comp.compButtonBar._buttonBarDesign2._primary ._button._selected, .comp.compButtonBar._buttonBarDesign3._primary ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Hover Background Color',
		dn: 'Button Bar Hover Background Color Secondary Background',
		n: 'buttonBarHoverBackgroundColorSecondaryBackground',
		dv: '<backgroundHoverColorTwo>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign2._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign3._secondary ._button:hover, .comp.compButtonBar._buttonBarDesign1._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign2._secondary ._button._selected, .comp.compButtonBar._buttonBarDesign3._secondary ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Hover Background Color',
		dn: 'Button Bar Hover Background Color Tertiary Background',
		n: 'buttonBarHoverBackgroundColorTertiaryBackground',
		dv: '<backgroundHoverColorThree>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign2._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign3._tertiary ._button:hover, .comp.compButtonBar._buttonBarDesign1._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign2._tertiary ._button._selected, .comp.compButtonBar._buttonBarDesign3._tertiary ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Hover Background Color',
		dn: 'Button Bar Hover Background Color Quatranary Background',
		n: 'buttonBarHoverBackgroundColorQuatranaryBackground',
		dv: '<backgroundHoverColorFour>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quaternary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quaternary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quaternary ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Hover Background Color',
		dn: 'Button Bar Hover Background Color Quinary Background',
		n: 'buttonBarHoverBackgroundColorQuinaryBackground',
		dv: '<backgroundHoverColorFive>',
		cp: 'background',
		sel: '.comp.compButtonBar._buttonBarDesign1._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign2._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign3._quinary ._button:hover, .comp.compButtonBar._buttonBarDesign1._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign2._quinary ._button._selected, .comp.compButtonBar._buttonBarDesign3._quinary ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Button Bar Text Color Hover Text Color',
		n: 'buttonBarTextColorHoverTextColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button:hover, .comp.compButtonBar._buttonBarDesign2 ._button:hover, .comp.compButtonBar._buttonBarDesign3 ._button:hover',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Button Bar Text Color Design 4 Hover Text Color',
		n: 'buttonBarTextColorDesign4HoverTextColor',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button:hover',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Button Bar Text Color Normal Text Color',
		n: 'buttonBarTextColorNormalTextColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button, .comp.compButtonBar._buttonBarDesign2 ._button, .comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Gap',
		dn: 'Button Bar Gap Design 3 Gap',
		n: 'buttonBarGapDesign3Gap',
		dv: '2px',
		cp: 'gap',
		sel: '.comp.compButtonBar._buttonBarDesign3',
		np: true,
	},
	{
		gn: 'Button Bar Gap',
		dn: 'Button Bar Gap Design 4 Gap',
		n: 'buttonBarGapDesign4Gap',
		dv: '2px',
		cp: 'gap',
		sel: '.comp.compButtonBar._buttonBarDesign4',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Primary Button Bar Text Color',
		n: 'primaryButtonBarTextColor',
		dv: '<backgroundColorOne>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._primary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Secondary Button Bar Text Color',
		n: 'secondaryButtonBarTextColor',
		dv: '<backgroundColorTwo>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._secondary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Tertiary Button Bar Text Color',
		n: 'tertiaryButtonBarTextColor',
		dv: '<backgroundColorThree>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._tertiary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Quatranary Button Bar Text Color',
		n: 'quatranaryButtonBarTextColor',
		dv: '<backgroundColorFour>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._quaternary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Text Color',
		dn: 'Quinary Button Bar Text Color',
		n: 'quinaryButtonBarTextColor',
		dv: '<backgroundColorFive>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._quinary ._button',
		np: true,
	},
	{
		gn: 'Button Bar Text Hover Color',
		dn: 'Button Bar Text Hover Color Design 4',
		n: 'buttonBarTextHoverColorDesign4',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._primary ._button:hover,.comp.compButtonBar._buttonBarDesign4._secondary ._button:hover,.comp.compButtonBar._buttonBarDesign4._tertiary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quaternary ._button:hover,.comp.compButtonBar._buttonBarDesign4._quinary ._button:hover',
		np: true,
	},
	{
		gn: 'Button Bar Cursor',
		dn: 'Button Bar Cursor All Designs',
		n: 'buttonBarCursorAllDesigns',
		dv: 'pointer',
		cp: 'cursor',
		sel: '.comp.compButtonBar ._button',
		np: true,
	},
	{
		gn: 'Text Color Hover',
		dn: 'ButtonBar Text hoverSelected',
		n: 'buttonBarTexthoverSelected',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4._primary ._button._selected,.comp.compButtonBar._buttonBarDesign4._secondary ._button._selected,.comp.compButtonBar._buttonBarDesign4._tertiary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quaternary ._button._selected,.comp.compButtonBar._buttonBarDesign4._quinary ._button._selected',
		np: true,
	},
	{
		gn: 'Text Color Selected',
		dn: 'Text Color SelectedDesigns 1 2 3',
		n: 'textColorSelectedDesigns123',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button._selected, .comp.compButtonBar._buttonBarDesign2 ._button._selected, .comp.compButtonBar._buttonBarDesign3 ._button._selected',
		np: true,
	},
	{
		gn: 'Text Color Selected',
		dn: 'Text Color SelectedDesigns 4',
		n: 'textColorSelectedDesigns4',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button._selected',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Bar Border',
		n: 'buttonBarDesignOneBorderBarBorder',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign1',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Button Border',
		n: 'buttonBarDesignOneBorderButtonBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Button Border Top',
		n: 'buttonBarDesignOneBorderButtonBorderTop',
		cp: 'border-top',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Button Border Right',
		n: 'buttonBarDesignOneBorderButtonBorderRight',
		cp: 'border-right',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Button Border Bottom',
		n: 'buttonBarDesignOneBorderButtonBorderBottom',
		cp: 'border-bottom',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design One Border',
		dn: 'Button Bar Design One Border Button Border Left',
		n: 'buttonBarDesignOneBorderButtonBorderLeft',
		cp: 'border-left',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Bar Border',
		n: 'buttonBarDesignTwoBorderBarBorder',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign2',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Button Border',
		n: 'buttonBarDesignTwoBorderButtonBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Button Border Top',
		n: 'buttonBarDesignTwoBorderButtonBorderTop',
		cp: 'border-top',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Button Border Right',
		n: 'buttonBarDesignTwoBorderButtonBorderRight',
		cp: 'border-right',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Button Border Bottom',
		n: 'buttonBarDesignTwoBorderButtonBorderBottom',
		cp: 'border-bottom',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Two Border',
		dn: 'Button Bar Design Two Border Button Border Left',
		n: 'buttonBarDesignTwoBorderButtonBorderLeft',
		cp: 'border-left',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Bar Border',
		n: 'buttonBarDesignThreeBorderBarBorder',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign3',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Button Border',
		n: 'buttonBarDesignThreeBorderButtonBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Button Border Top',
		n: 'buttonBarDesignThreeBorderButtonBorderTop',
		cp: 'border-top',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Button Border Right',
		n: 'buttonBarDesignThreeBorderButtonBorderRight',
		cp: 'border-right',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Button Border Bottom',
		n: 'buttonBarDesignThreeBorderButtonBorderBottom',
		cp: 'border-bottom',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Three Border',
		dn: 'Button Bar Design Three Border Button Border Left',
		n: 'buttonBarDesignThreeBorderButtonBorderLeft',
		cp: 'border-left',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Bar Border',
		n: 'buttonBarDesignFourBorderBarBorder',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign4',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Button Border',
		n: 'buttonBarDesignFourBorderButtonBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Button Border Top',
		n: 'buttonBarDesignFourBorderButtonBorderTop',
		cp: 'border-top',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Button Border Right',
		n: 'buttonBarDesignFourBorderButtonBorderRight',
		cp: 'border-right',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Button Border Bottom',
		n: 'buttonBarDesignFourBorderButtonBorderBottom',
		cp: 'border-bottom',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Design Four Border',
		dn: 'Button Bar Design Four Border Button Border Left',
		n: 'buttonBarDesignFourBorderButtonBorderLeft',
		cp: 'border-left',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border RadiusDesign 1 Shorthand',
		n: 'buttonBarBorderRadiusDesign1Shorthand',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign1',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design OneTop Left',
		n: 'buttonBarBorderRadiusDesignOneTopLeft',
		cp: 'border-top-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button._firstChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design OneBottom Left',
		n: 'buttonBarBorderRadiusDesignOneBottomLeft',
		cp: 'border-bottom-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button._first-child',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design OneBottom Right',
		n: 'buttonBarBorderRadiusDesignOneBottomRight',
		cp: 'border-bottom-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button._lastChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design OneTop Right',
		n: 'buttonBarBorderRadiusDesignOneTopRight',
		cp: 'border-top-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign1 ._button._lastChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border RadiusDesign Two Shorthand',
		n: 'buttonBarBorderRadiusDesignTwoShorthand',
		dv: '30px',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign2',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Two Top Left',
		n: 'buttonBarBorderRadiusDesignTwoTopLeft',
		dv: '16px',
		cp: 'border-top-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button._firstChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Two Bottom Left',
		n: 'buttonBarBorderRadiusDesignTwoBottomLeft',
		dv: '16px',
		cp: 'border-bottom-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button._firstChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Two Bottom Right',
		n: 'buttonBarBorderRadiusDesignTwoBottomRight',
		dv: '16px',
		cp: 'border-bottom-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button._lastChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Two Top Right',
		n: 'buttonBarBorderRadiusDesignTwoTopRight',
		dv: '16px',
		cp: 'border-top-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign2 ._button._lastChild',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border RadiusDesign Three Shorthand',
		n: 'buttonBarBorderRadiusDesignThreeShorthand',
		dv: '30px',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Three Top Left',
		n: 'buttonBarBorderRadiusDesignThreeTopLeft',
		cp: 'border-top-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Three Bottom Left',
		n: 'buttonBarBorderRadiusDesignThreeBottomLeft',
		cp: 'border-bottom-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Three Bottom Right',
		n: 'buttonBarBorderRadiusDesignThreeBottomRight',
		cp: 'border-bottom-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Three Top Right',
		n: 'buttonBarBorderRadiusDesignThreeTopRight',
		cp: 'border-top-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Three Button',
		n: 'buttonBarBorderRadiusDesignThreeButton',
		dv: '30px',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign3 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border RadiusDesign Four Shorthand',
		n: 'buttonBarBorderRadiusDesignFourShorthand',
		dv: '40px',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Four Top Left',
		n: 'buttonBarBorderRadiusDesignFourTopLeft',
		cp: 'border-top-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Four Bottom Left',
		n: 'buttonBarBorderRadiusDesignFourBottomLeft',
		cp: 'border-bottom-left-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Four Bottom Right',
		n: 'buttonBarBorderRadiusDesignFourBottomRight',
		cp: 'border-bottom-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Button Bar Border Radius Design Four Top Right',
		n: 'buttonBarBorderRadiusDesignFourTopRight',
		cp: 'border-top-right-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Button Bar Border Radius',
		dn: 'Design 4 Button border radius',
		n: 'design4Buttonborderradius',
		dv: '40px',
		cp: 'border-radius',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
	{
		gn: 'Design4',
		dn: 'Design4 Background color ',
		n: 'ButtonBarDesign4backgroundColor',
		dv: '<backgroundColorTen>',
		cp: 'background-color',
		sel: '.comp.compButtonBar._buttonBarDesign4 ._button',
		np: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
