import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ dn: 'Link Font', n: 'linkFont', dv: '<primaryFont>', np: true },

	{
		gn: 'Default',
		dn: 'Default Link Font',
		n: 'defaultLinkFont',
		dv: '<linkFont>',
		cp: 'font',
		sel: '.comp.compLink._default',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Font',
		n: 'underLineLinkFont',
		dv: '<linkFont>',
		cp: 'font',
		sel: '.comp.compLink._underLine',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under n Above Link Font',
		n: 'undernAboveLinkFont',
		dv: '<linkFont>',
		cp: 'font',
		sel: '.comp.compLink._underAboveLine',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'SideLines Link Font',
		n: 'sideLinesLinkFont',
		dv: '<linkFont>',
		cp: 'font',
		sel: '.comp.compLink._sideLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Link Padding',
		n: 'defaultLinkPadding',
		cp: 'padding',
		sel: '.comp.compLink._default',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Padding',
		n: 'underLineLinkPadding',
		cp: 'padding',
		sel: '.comp.compLink._underLine',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Link Padding',
		n: 'underAboveLineLinkPadding',
		cp: 'padding',
		sel: '.comp.compLink._underAboveLine',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Link Padding',
		n: 'sideLineLinkPadding',
		dv: '0px 5px',
		cp: 'padding',
		sel: '.comp.compLink._sideLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Link Margin',
		n: 'defaultLinkMargin',
		cp: 'margin',
		sel: '.comp.compLink._default',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Margin',
		n: 'underLineLinkMargin',
		cp: 'margin',
		sel: '.comp.compLink._underLine',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Link Margin',
		n: 'underAboveLineLinkMargin',
		cp: 'margin',
		sel: '.comp.compLink._underAboveLine',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Link Margin',
		n: 'sideLineLinkMargin',
		cp: 'margin',
		sel: '.comp.compLink._sideLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Link Text Decoration',
		n: 'defaultLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._default',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Text Decoration',
		n: 'underLineLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._underLine',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Link Text Decoration',
		n: 'underAboveLineLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._underAboveLine',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Link Text Decoration',
		n: 'sideLineLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._sideLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Hover Link Text Decoration',
		n: 'defaultHoverLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._default:hover, .comp.compLink._default._showLines',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Hover Link Text Decoration',
		n: 'underLineHoverLinkTextDecoration',
		dv: 'underline',
		cp: 'text-decoration',
		sel: '.comp.compLink._underLine:hover, .comp.compLink._underLine._showLines',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Hover Link Text Decoration',
		n: 'underAboveLineHoverLinkTextDecoration',
		dv: 'underline overline',
		cp: 'text-decoration',
		sel: '.comp.compLink._underAboveLine:hover, .comp.compLink._underAboveLine._showLines',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Hover Link Text Decoration',
		n: 'sideLineHoverLinkTextDecoration',
		dv: 'none',
		cp: 'text-decoration',
		sel: '.comp.compLink._sideLines:hover, .comp.compLink._sideLines._showLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Link Border',
		n: 'defaultLinkBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._default',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Border',
		n: 'underLineLinkBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._underLine',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Link Border',
		n: 'underAboveLineLinkBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._underAboveLine',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Link Border',
		n: 'sideLineLinkBorder',
		dv: 'none, 1px solid transparent, none, 1px solid transparent',
		cp: 'border',
		sel: '.comp.compLink._sideLines',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Link Hover Border',
		n: 'defaultLinkHoverBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._default:hover, .comp.compLink._default._showLines',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Under Line Link Hover Border',
		n: 'underLineLinkHoverBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._underLine:hover, .comp.compLink._underLine._showLines',
		np: true,
	},
	{
		gn: 'Under Above Line',
		dn: 'Under Above Line Link Hover Border',
		n: 'underAboveLineLinkHoverBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compLink._underAboveLine:hover, .comp.compLink._underAboveLine._showLines',
		np: true,
	},
	{
		gn: 'Side Line',
		dn: 'Side Line Link Hover Border',
		n: 'sideLineLinkHoverBorder',
		dv: 'none, 1px solid, none, 1px solid',
		cp: 'border',
		sel: '.comp.compLink._sideLines:hover, .comp.compLink._sideLines._showLines',
		np: true,
	},

	{
		gn: 'Line Color',
		dn: 'Primary Link Border Color',
		n: 'primaryLinkBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary:hover, .comp.compLink._sideLines._primary._showLines',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Secondary Link Border Color',
		n: 'secondaryLinkBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary:hover, .comp.compLink._sideLines._secondary._showLines',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Tertiary Link Border Color',
		n: 'tertiaryLinkBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary:hover, .comp.compLink._sideLines._tertiary._showLines',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quaternary Link Border Color',
		n: 'quaternaryLinkBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary:hover, .comp.compLink._sideLines._quaternary._showLines',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quinary Link Border Color',
		n: 'quinaryLinkBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary:hover, .comp.compLink._sideLines._quinary._showLines',
		np: true,
	},

	{
		gn: 'Color',
		dn: 'Primary Link Font Color',
		n: 'primaryLinkFontColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Secondary Link Font Color',
		n: 'secondaryLinkFontColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Tertiary Link Font Color',
		n: 'tertiaryLinkFontColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quaternary Link Font Color',
		n: 'quaternaryLinkFontColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quinary Link Font Color',
		n: 'quinaryLinkFontColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary',
		np: true,
	},

	{
		gn: 'Line Color',
		dn: 'Primary Text Decoration Color',
		n: 'primaryTextDecorationColor',
		dv: '<fontColorThree>',
		cp: 'text-decoration-color',
		sel: '.comp.compLink._default._primary, .comp.compLink._underLine._primary, .comp.compLink._underAboveLine._primary, .comp.compLink._sideLines._primary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Secondary Text Decoration Color',
		n: 'secondaryTextDecorationColor',
		dv: '<fontColorFour>',
		cp: 'text-decoration-color',
		sel: '.comp.compLink._default._secondary, .comp.compLink._underLine._secondary, .comp.compLink._underAboveLine._secondary, .comp.compLink._sideLines._secondary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Tertiary Text Decoration Color',
		n: 'tertiaryTextDecorationColor',
		dv: '<fontColorFive>',
		cp: 'text-decoration-color',
		sel: '.comp.compLink._default._tertiary, .comp.compLink._underLine._tertiary, .comp.compLink._underAboveLine._tertiary, .comp.compLink._sideLines._tertiary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quaternary Text Decoration Color',
		n: 'quaternaryTextDecorationColor',
		dv: '<fontColorNine>',
		cp: 'text-decoration-color',
		sel: '.comp.compLink._default._quaternary, .comp.compLink._underLine._quaternary, .comp.compLink._underAboveLine._quaternary, .comp.compLink._sideLines._quaternary',
		np: true,
	},
	{
		gn: 'Line Color',
		dn: 'Quinary Text Decoration Color',
		n: 'quinaryTextDecorationColor',
		dv: '<fontColorSeven>',
		cp: 'text-decoration-color',
		sel: '.comp.compLink._default._quinary, .comp.compLink._underLine._quinary, .comp.compLink._underAboveLine._quinary, .comp.compLink._sideLines._quinary',
		np: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
