import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		gn: 'Jot Color',
		dn: 'Default Jot Color',
		n: 'defaultJotColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compJot._defaultJot._default, .comp.compJot._defaultJot._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Light Jot Color',
		n: 'lightJotColor',
		dv: '<fontColorSix>',
		cp: 'color',
		sel: '.comp.compJot._lightJot._default, .comp.compJot._lightJot._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Primary Jot Color',
		n: 'primaryJotColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compJot._primary._default, .comp.compJot._primary._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Secondary Jot Color',
		n: 'secondaryJotColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compJot._secondary._default , .comp.compJot._secondary._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Tertiary Jot Color',
		n: 'tertiaryJotColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compJot._tertiary._default, .comp.compJot._tertiary._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Quaternary Jot Color',
		n: 'quaternaryJotColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compJot._quaternary._default, .comp.compJot._quaternary._outlined',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Quinary Jot Color',
		n: 'quinaryJotColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compJot._quinary._default, .comp.compJot._quinary._outlined',
		np: true,
	},

	{
		gn: 'Jot Border Color',
		dn: 'Default Jot Border Color',
		n: 'defaultJotBorderColor',
		dv: '<fontColorOne>',
		cp: 'border-color',
		sel: '.comp.compJot._defaultJot',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Light Jot Border Color',
		n: 'lightJotBorderColor',
		dv: '<fontColorSix>',
		cp: 'border-color',
		sel: '.comp.compJot._lightJot',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Primary Menu Border Color',
		n: 'primaryMenuBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compJot._primary',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Secondary Menu Border Color',
		n: 'secondaryMenuBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compJot._secondary',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Tertiary Menu Border Color',
		n: 'tertiaryMenuBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compJot._tertiary',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Quaternary Menu Border Color',
		n: 'quaternaryMenuBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compJot._quaternary',
		np: true,
	},
	{
		gn: 'Jot Border Color',
		dn: 'Quinary Menu Border Color',
		n: 'quinaryMenuBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compJot._quinary',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Jot Border',
		n: 'defaultJotBorder',
		cp: 'border',
		sel: '.comp.compJot._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Jot Border',
		n: 'outlineJotBorder',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compJot._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Jot Border',
		n: 'filledJotBorder',
		cp: 'border',
		sel: '.comp.compJot._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Jot Border',
		n: 'roundedJotBorder',
		cp: 'border',
		sel: '.comp.compJot._rounded',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Jot Border Radius',
		n: 'defaultJotBorderRadius',
		cp: 'border-radius',
		sel: '.comp.compJot._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Jot Border Radius',
		n: 'outlineJotBorderRadius',
		dv: '3px',
		cp: 'border-radius',
		sel: '.comp.compJot._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Jot Border Radius',
		n: 'filledJotBorderRadius',
		dv: '3px',
		cp: 'border-radius',
		sel: '.comp.compJot._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Jot Border Radius',
		n: 'roundedJotBorderRadius',
		dv: '50%',
		cp: 'border-radius',
		sel: '.comp.compJot._rounded',
		np: true,
	},

	{
		gn: 'Jot Filled Background Color',
		dn: 'Default Jot Background Color',
		n: 'defaultJotBackgroundColor',
		dv: '<fontColorOne>',
		cp: 'background',
		sel: '.comp.compJot._defaultJot._filled, .comp.compJot._defaultJot._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Light Jot Background Color',
		n: 'lightJotBackgroundColor',
		dv: '<backgroundColorNine>',
		cp: 'background',
		sel: '.comp.compJot._lightJot._filled, .comp.compJot._lightJot._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Primary Jot Background Color',
		n: 'primaryJotBackgroundColor',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compJot._primary._filled, .comp.compJot._primary._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Secondary Jot Background Color',
		n: 'secondaryJotBackgroundColor',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compJot._secondary._filled , .comp.compJot._secondary._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Tertiary Jot Background Color',
		n: 'tertiaryJotBackgroundColor',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compJot._tertiary._filled, .comp.compJot._tertiary._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Quaternary Jot Background Color',
		n: 'quaternaryJotBackgroundColor',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compJot._quaternary._filled, .comp.compJot._quaternary._rounded',
		np: true,
	},
	{
		gn: 'Jot Filled Background Color',
		dn: 'Quinary Jot Background Color',
		n: 'quinaryJotBackgroundColor',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compJot._quinary._filled, .comp.compJot._quinary._rounded',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Jot Font Size',
		n: 'defaultJotFontSize',
		dv: '16px',
		cp: 'font-size',
		sel: '.comp.compJot._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Jot Font Size',
		n: 'outlineJotFontSize',
		dv: '16px',
		cp: 'font-size',
		sel: '.comp.compJot._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Jot Font Size',
		n: 'filledJotFontSize',
		dv: '16px',
		cp: 'font-size',
		sel: '.comp.compJot._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Jot Font Size',
		n: 'roundedJotFontSize',
		dv: '16px',
		cp: 'font-size',
		sel: '.comp.compJot._rounded',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Jot Padding Size',
		n: 'defaultJotPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compJot._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Jot Padding Size',
		n: 'outlineJotPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compJot._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Jot Padding Size',
		n: 'filledJotPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compJot._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Jot Padding Size',
		n: 'roundedJotPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compJot._rounded',
		np: true,
	},

	{
		gn: 'Jot Color',
		dn: 'Default Jot Filled and Rounded Color',
		n: 'defaultJotFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compJot._defaultJot._filled, .comp.compJot._defaultJot._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Light Jot Filled and Rounded Color',
		n: 'lightJotFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compJot._lightJot._filled, .comp.compJot._lightJot._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Primary Jot Filled and Rounded Color',
		n: 'primaryJotFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compJot._primary._filled, .comp.compJot._primary._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Secondary Jot Filled and Rounded Color',
		n: 'secondaryJotFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compJot._secondary._filled , .comp.compJot._secondary._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Tertiary Jot Filled and Rounded Color',
		n: 'tertiaryJotFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compJot._tertiary._filled, .comp.compJot._tertiary._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Quaternary Jot Filled and Rounded Color',
		n: 'quaternaryJotFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compJot._quaternary._filled, .comp.compJot._quaternary._rounded',
		np: true,
	},
	{
		gn: 'Jot Color',
		dn: 'Quinary Jot Filled and Rounded Color',
		n: 'quinaryJotFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compJot._quinary._filled, .comp.compJot._quinary._rounded',
		np: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
