import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		gn: 'Icon Color',
		dn: 'Default Icon Color',
		n: 'defaultIconColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compIcon._defaultIcon._default, .comp.compIcon._defaultIcon._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Light Icon Color',
		n: 'lightIconColor',
		dv: '<fontColorSix>',
		cp: 'color',
		sel: '.comp.compIcon._lightIcon._default, .comp.compIcon._lightIcon._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Primary Icon Color',
		n: 'primaryIconColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compIcon._primary._default, .comp.compIcon._primary._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Secondary Icon Color',
		n: 'secondaryIconColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compIcon._secondary._default , .comp.compIcon._secondary._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Tertiary Icon Color',
		n: 'tertiaryIconColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compIcon._tertiary._default, .comp.compIcon._tertiary._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Quaternary Icon Color',
		n: 'quaternaryIconColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compIcon._quaternary._default, .comp.compIcon._quaternary._outlined',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Quinary Icon Color',
		n: 'quinaryIconColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compIcon._quinary._default, .comp.compIcon._quinary._outlined',
		np: true,
	},

	{
		gn: 'Icon Border Color',
		dn: 'Default Icon Border Color',
		n: 'defaultIconBorderColor',
		dv: '<fontColorOne>',
		cp: 'border-color',
		sel: '.comp.compIcon._defaultIcon',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Light Icon Border Color',
		n: 'lightIconBorderColor',
		dv: '<fontColorSix>',
		cp: 'border-color',
		sel: '.comp.compIcon._lightIcon',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Primary Menu Border Color',
		n: 'primaryMenuBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compIcon._primary',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Secondary Menu Border Color',
		n: 'secondaryMenuBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compIcon._secondary',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Tertiary Menu Border Color',
		n: 'tertiaryMenuBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compIcon._tertiary',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Quaternary Menu Border Color',
		n: 'quaternaryMenuBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compIcon._quaternary',
		np: true,
	},
	{
		gn: 'Icon Border Color',
		dn: 'Quinary Menu Border Color',
		n: 'quinaryMenuBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compIcon._quinary',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Icon Border',
		n: 'defaultIconBorder',
		cp: 'border',
		sel: '.comp.compIcon._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Icon Border',
		n: 'outlineIconBorder',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compIcon._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Icon Border',
		n: 'filledIconBorder',
		cp: 'border',
		sel: '.comp.compIcon._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Icon Border',
		n: 'roundedIconBorder',
		cp: 'border',
		sel: '.comp.compIcon._rounded',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Icon Border Radius',
		n: 'defaultIconBorderRadius',
		cp: 'border-radius',
		sel: '.comp.compIcon._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Icon Border Radius',
		n: 'outlineIconBorderRadius',
		dv: '3px',
		cp: 'border-radius',
		sel: '.comp.compIcon._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Icon Border Radius',
		n: 'filledIconBorderRadius',
		dv: '3px',
		cp: 'border-radius',
		sel: '.comp.compIcon._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Icon Border Radius',
		n: 'roundedIconBorderRadius',
		dv: '50%',
		cp: 'border-radius',
		sel: '.comp.compIcon._rounded',
		np: true,
	},

	{
		gn: 'Icon Filled Background Color',
		dn: 'Default Icon Background Color',
		n: 'defaultIconBackgroundColor',
		dv: '<fontColorOne>',
		cp: 'background',
		sel: '.comp.compIcon._defaultIcon._filled, .comp.compIcon._defaultIcon._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Light Icon Background Color',
		n: 'lightIconBackgroundColor',
		dv: '<backgroundColorNine>',
		cp: 'background',
		sel: '.comp.compIcon._lightIcon._filled, .comp.compIcon._lightIcon._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Primary Icon Background Color',
		n: 'primaryIconBackgroundColor',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compIcon._primary._filled, .comp.compIcon._primary._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Secondary Icon Background Color',
		n: 'secondaryIconBackgroundColor',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compIcon._secondary._filled , .comp.compIcon._secondary._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Tertiary Icon Background Color',
		n: 'tertiaryIconBackgroundColor',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compIcon._tertiary._filled, .comp.compIcon._tertiary._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Quaternary Icon Background Color',
		n: 'quaternaryIconBackgroundColor',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compIcon._quaternary._filled, .comp.compIcon._quaternary._rounded',
		np: true,
	},
	{
		gn: 'Icon Filled Background Color',
		dn: 'Quinary Icon Background Color',
		n: 'quinaryIconBackgroundColor',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compIcon._quinary._filled, .comp.compIcon._quinary._rounded',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Icon Padding Size',
		n: 'defaultIconPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compIcon._default',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Icon Padding Size',
		n: 'outlineIconPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compIcon._outlined',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Icon Padding Size',
		n: 'filledIconPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compIcon._filled',
		np: true,
	},
	{
		gn: 'Rounded',
		dn: 'Rounded Icon Padding Size',
		n: 'roundedIconPaddingSize',
		dv: '6px',
		cp: 'padding',
		sel: '.comp.compIcon._rounded',
		np: true,
	},

	{
		gn: 'Icon Color',
		dn: 'Default Icon Filled and Rounded Color',
		n: 'defaultIconFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compIcon._defaultIcon._filled, .comp.compIcon._defaultIcon._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Light Icon Filled and Rounded Color',
		n: 'lightIconFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compIcon._lightIcon._filled, .comp.compIcon._lightIcon._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Primary Icon Filled and Rounded Color',
		n: 'primaryIconFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compIcon._primary._filled, .comp.compIcon._primary._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Secondary Icon Filled and Rounded Color',
		n: 'secondaryIconFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compIcon._secondary._filled , .comp.compIcon._secondary._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Tertiary Icon Filled and Rounded Color',
		n: 'tertiaryIconFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compIcon._tertiary._filled, .comp.compIcon._tertiary._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Quaternary Icon Filled and Rounded Color',
		n: 'quaternaryIconFilledRoundedColor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compIcon._quaternary._filled, .comp.compIcon._quaternary._rounded',
		np: true,
	},
	{
		gn: 'Icon Color',
		dn: 'Quinary Icon Filled and Rounded Color',
		n: 'quinaryIconFilledRoundedColor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compIcon._quinary._filled, .comp.compIcon._quinary._rounded',
		np: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
