import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		gn: 'Font',
		dn: 'Tabs Name Font',
		n: 'tabsTitleFont',
		dv: '<primaryFont>',
		cp: 'font',
		sel: '.tabDiv',
	},

	{
		gn: 'Background',
		dn: 'Tab Child Container Background Default Design',
		n: 'tabChildContainerBackgroundDefaultDesign',
		dv: '#FCFCFC',
		cp: 'background',
		sel: '.comp.compTabs._default > .tabGridDiv',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Tab Child Container Background Line Desgin',
		n: 'tabChildContainerBackgroundLineDesgin',
		dv: '#FCFCFC',
		cp: 'background',
		sel: '.comp.compTabs._line > .tabGridDiv',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Tab Child Container Background Highlight Design',
		n: 'tabChildContainerBackgroundHighlightDesign',
		dv: '#FCFCFC',
		cp: 'background',
		sel: '.comp.compTabs._highlight > .tabGridDiv',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Tab Child Container Background Underline Design',
		n: 'tabChildContainerBackgroundUnderlineDesign',
		dv: 'transparent',
		cp: 'background',
		sel: '.comp.compTabs._underLine > .tabGridDiv',
		np: true,
	},

	{
		gn: 'Background',
		dn: 'Tabs Container Background',
		n: 'tabsContainerBackground',
		dv: 'transparent',
		cp: 'background',
		sel: '.tabsContainer',
	},

	{
		gn: 'Gap',
		dn: 'Gap between tabs Default Desgin',
		n: 'gapbetweentabsDefaultDesgin',
		dv: '0px',
		cp: 'gap',
		sel: '.comp.compTabs._default > .tabsContainer',
		np: true,
	},
	{
		gn: 'Gap',
		dn: 'Gap between tabs Line Desgin',
		n: 'gapbetweentabsLineDesgin',
		dv: '0px',
		cp: 'gap',
		sel: '.comp.compTabs._line > .tabsContainer',
		np: true,
	},
	{
		gn: 'Gap',
		dn: 'Gap between tabs Highlight Desgin',
		n: 'gapbetweentabsHighlightDesgin',
		dv: '0px',
		cp: 'gap',
		sel: '.comp.compTabs._highlight > .tabsContainer',
		np: true,
	},
	{
		gn: 'Gap',
		dn: 'Gap between tabs Underline Desgin',
		n: 'gapbetweentabsUnderlineDesgin',
		dv: '10px',
		cp: 'gap',
		sel: '.comp.compTabs._underLine > .tabsContainer',
		np: true,
	},

	{
		gn: 'Gap',
		dn: 'Tab Name Gap',
		n: 'tabNameGap',
		dv: '5px',
		cp: 'gap',
		sel: '.tabDiv',
	},
	{
		gn: 'Padding',
		dn: 'Tab Child Container Padding',
		n: 'tabChildContainerPadding',
		dv: '5px',
		cp: 'padding',
		sel: '.tabGridDiv',
	},

	{
		gn: 'Default',
		dn: 'Default Tab Horizontal Border',
		n: 'defaultTabHorizontalBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._default._horizontal > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Horizonatal Border',
		n: 'lineTabHorizonatalBorder',
		dv: '2px solid, none, none, none',
		cp: 'border',
		sel: '.comp.compTabs._line._horizontal  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Horizonatal Border',
		n: 'hightlightTabHorizonatalBorder',
		dv: '4px solid transparent',
		cp: 'border',
		sel: '.comp.compTabs._highlight._horizontal > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'UnderLine Tab Horizonatal Border',
		n: 'underLineTabHorizonatalBorder',
		dv: 'none, none, 3px solid, none',
		cp: 'border',
		sel: '.comp.compTabs._underLine._horizontal > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Vertical Border',
		n: 'defaultTabVerticalBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._default._vertical > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Vertical Border',
		n: 'lineTabVerticalBorder',
		dv: 'none, none, none, 2px solid',
		cp: 'border',
		sel: '.comp.compTabs._line._vertical > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Vertical Border',
		n: 'hightlightTabVerticalBorder',
		dv: '4px solid transparent',
		cp: 'border',
		sel: '.comp.compTabs._highlight._vertical > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'UnderLine Tab Vertical Border',
		n: 'underLineTabVerticalBorder',
		dv: 'none, 3px solid, none, none',
		cp: 'border',
		sel: '.comp.compTabs._underLine._vertical > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Horizontal Tabs Seperator',
		n: 'defaultTabHorizontalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._default._horizontal > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Horizonatal Tabs Seperator',
		n: 'lineTabHorizonatalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._line._horizontal  > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Horizonatal Tabs Seperator',
		n: 'hightlightTabHorizonatalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._highlight._horizontal > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'UnderLine Tab Horizonatal Tabs Seperator',
		n: 'underLineTabHorizonatalTabsSeperator',
		dv: 'none, none, 1px solid <borderColorSix>, none',
		cp: 'border',
		sel: '.comp.compTabs._underLine._horizontal > .tabsContainer > .tabsSeperator',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Vertical Tabs Seperator',
		n: 'defaultTabVerticalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._default._vertical > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Vertical Tabs Seperator',
		n: 'lineTabVerticalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._line._vertical > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Vertical Tabs Seperator',
		n: 'hightlightTabVerticalTabsSeperator',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compTabs._highlight._vertical > .tabsContainer > .tabsSeperator',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'UnderLine Tab Vertical Tabs Seperator',
		n: 'underLineTabVerticalTabsSeperator',
		dv: 'none, 1px solid <borderColorSix>, none, none',
		cp: 'border',
		sel: '.comp.compTabs._underLine._vertical > .tabsContainer > .tabsSeperator',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Horizontal Padding',
		n: 'defaultTabHorizontalPadding',
		dv: '3px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._default._horizontal > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Horizontal Padding',
		n: 'lineTabHorizontalPadding',
		dv: '3px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._line._horizontal > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Horizontal Padding',
		n: 'hightlightTabHorizontalPadding',
		dv: '8px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._highlight._horizontal > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Underline Tab Horizontal Padding',
		n: 'underlineTabHorizontalPadding',
		dv: '5px 0px',
		cp: 'padding',
		sel: '.comp.compTabs._underLine._horizontal > .tabsContainer > .tabDiv',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Vertical Padding',
		n: 'defaultTabVerticalPadding',
		dv: '3px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._default._vertical > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Vertical Padding',
		n: 'lineTabVerticalPadding',
		dv: '3px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._line._vertical > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Vertical Padding',
		n: 'hightlightTabVerticalPadding',
		dv: '8px 8px',
		cp: 'padding',
		sel: '.comp.compTabs._highlight._vertical > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Under Line',
		dn: 'Underline Tab Vertical Padding',
		n: 'underlineTabVerticalPadding',
		dv: '0px 5px',
		cp: 'padding',
		sel: '.comp.compTabs._underLine._vertical > .tabsContainer > .tabDiv',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Background',
		n: 'defaultTabBackground',
		dv: '<tabChildContainerBackground>',
		cp: 'background',
		sel: '.comp.compTabs._default > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Background',
		n: 'lineTabBackground',
		dv: '<tabChildContainerBackground>',
		cp: 'background',
		sel: '.comp.compTabs._line > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Background',
		dn: 'Primary Highlight Tab Background',
		n: 'primaryHighlightTabBackground',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compTabs._highlight._primary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Secondary Highlight Tab Background',
		n: 'secondaryHighlightTabBackground',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compTabs._highlight._secondary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Tertiary Highlight Tab Background',
		n: 'tertiaryHighlightTabBackground',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compTabs._highlight._tertiary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Quaternary Highlight Tab Background',
		n: 'quaternaryHighlightTabBackground',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compTabs._highlight._quaternary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Background',
		dn: 'Quinary Highlight Tab Background',
		n: 'quinaryHighlightTabBackground',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compTabs._highlight._quinary  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Vertical Border Radius',
		n: 'defaultTabVerticalBorderRadius',
		dv: '3px 0px 0px 3px',
		cp: 'border-radius',
		sel: '.comp.compTabs._default._vertical  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Vertical Border Radius',
		n: 'lineTabVerticalBorderRadius',
		dv: 'none',
		cp: 'border-radius',
		sel: '.comp.compTabs._line._vertical  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Vertical Border Radius',
		n: 'hightlightTabVerticalBorderRadius',
		dv: '4px',
		cp: 'border-radius',
		sel: '.comp.compTabs._highlight._vertical  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Horizontal Border Radius',
		n: 'defaultTabHorizontalBorderRadius',
		dv: '3px 3px 0px 0px',
		cp: 'border-radius',
		sel: '.comp.compTabs._default._horizontal  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Horizontal Border Radius',
		n: 'lineTabHorizontalBorderRadius',
		dv: 'none',
		cp: 'border-radius',
		sel: '.comp.compTabs._line._horizontal  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Hightlight Tab Horizontal Border Radius',
		n: 'hightlightTabHorizontalBorderRadius',
		dv: '4px',
		cp: 'border-radius',
		sel: '.comp.compTabs._highlight._horizontal  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Tab Highlighter Scale',
		n: 'defaultTabHighlighterScale',
		cp: 'transform',
		sel: '.comp.compTabs._default  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Line',
		dn: 'Line Tab Highlighter Scale',
		n: 'lineTabHighlighterScale',
		cp: 'transform',
		sel: '.comp.compTabs._line  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Highlight',
		dn: 'Highlight Tab Highlighter Scale',
		n: 'highlightTabHighlighterScale',
		dv: 'scale(0.8)',
		cp: 'transform',
		sel: '.comp.compTabs._highlight  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Primary Line Tab Border Color',
		n: 'primaryLineTabBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compTabs._line._primary  > .tabsContainer > .tabHighlighter, .comp.compTabs._underLine._primary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Secondary Line Tab Border Color',
		n: 'secondaryLineTabBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compTabs._line._secondary  > .tabsContainer > .tabHighlighter, .comp.compTabs._underLine._secondary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Tertiary Line Tab Border Color',
		n: 'tertiaryLineTabBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compTabs._line._tertiary  > .tabsContainer > .tabHighlighter, .comp.compTabs._underLine._tertiary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quaternary Line Tab Border Color',
		n: 'quaternaryLineTabBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compTabs._line._quaternary  > .tabsContainer > .tabHighlighter, .comp.compTabs._underLine._quaternary  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quinary Line Tab Border Color',
		n: 'quinaryLineTabBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compTabs._line._quinary  > .tabsContainer > .tabHighlighter, .comp.compTabs._underLine._quinary  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Color',
		dn: 'Quinary Default n Line Tab Active Color',
		n: 'quinaryDefaultnLineTabActiveColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compTabs._line._primary > .tabsContainer > .tabDiv._active, .comp.compTabs._default._primary > .tabsContainer > .tabDiv._active, .comp.compTabs._underLine._primary > .tabsContainer > .tabDiv._active',
		np: true,
	},
	{
		gn: 'Color',
		dn: ' Default n Line Tab Active Color',
		n: ' DefaultnLineTabActiveColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compTabs._line._secondary > .tabsContainer > .tabDiv._active, .comp.compTabs._default._secondary > .tabsContainer > .tabDiv._active, .comp.compTabs._underLine._secondary > .tabsContainer > .tabDiv._active',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Primary Default n Line Tab Active Color',
		n: 'primaryDefaultnLineTabActiveColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compTabs._line._tertiary > .tabsContainer > .tabDiv._active, .comp.compTabs._default._tertiary > .tabsContainer > .tabDiv._active, .comp.compTabs._underLine._tertiary > .tabsContainer > .tabDiv._active',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Secondary Default n Line Tab Active Color',
		n: 'secondaryDefaultnLineTabActiveColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compTabs._line._quaternary > .tabsContainer > .tabDiv._active, .comp.compTabs._default._quaternary > .tabsContainer > .tabDiv._active, .comp.compTabs._underLine._quaternary > .tabsContainer > .tabDiv._active',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Tertiary Default n Line Tab Active Color',
		n: 'tertiaryDefaultnLineTabActiveColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compTabs._line._quinary > .tabsContainer > .tabDiv._active, .comp.compTabs._default._quinary > .tabsContainer > .tabDiv._active, .comp.compTabs._underLine._quinary > .tabsContainer > .tabDiv._active',
		np: true,
	},

	{
		gn: 'Box shadow',
		dn: 'Tab Default Highlighter box shadow',
		n: 'tabDefaultHighlighterboxshadow',
		dv: '0px 0px 6px #DDD',
		cp: 'box-shadow',
		sel: '.comp.compTabs._default  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Box shadow',
		dn: 'Tab Line Highlighter box shadow',
		n: 'tabLineHighlighterboxshadow',
		dv: '0px 0px 6px #DDD',
		cp: 'box-shadow',
		sel: '.comp.compTabs._line  > .tabsContainer > .tabHighlighter',
		np: true,
	},
	{
		gn: 'Box shadow',
		dn: 'Tab Highlight Highlighter box shadow',
		n: 'tabHighlightHighlighterboxshadow',
		dv: '0px 0px 6px #DDD',
		cp: 'box-shadow',
		sel: '.comp.compTabs._highlight  > .tabsContainer > .tabHighlighter',
		np: true,
	},

	{
		gn: 'Color',
		dn: 'Default Design Color',
		n: 'defaultDesignColor',
		cp: 'color',
		sel: '.comp.compTabs._deafult > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Line Design Color',
		n: 'lineDesignColor',
		cp: 'color',
		sel: '.comp.compTabs._line > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Highlight Design Color',
		n: 'highlightDesignColor',
		cp: 'color',
		sel: '.comp.compTabs._highlight > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'UnderLline Design Color',
		n: 'underLlineDesignColor',
		dv: '<borderColorSix>',
		cp: 'color',
		sel: '.comp.compTabs._underLine > .tabsContainer > .tabDiv',
		np: true,
	},

	{
		gn: 'Color',
		dn: 'Default Design Font',
		n: 'defaultDesignFont',
		cp: 'font',
		sel: '.comp.compTabs._deafult > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Line Design Font',
		n: 'lineDesignFont',
		cp: 'font',
		sel: '.comp.compTabs._line > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'Highlight Design Font',
		n: 'highlightDesignFont',
		cp: 'font',
		sel: '.comp.compTabs._highlight > .tabsContainer > .tabDiv',
		np: true,
	},
	{
		gn: 'Color',
		dn: 'UnderLline Design Font',
		n: 'underLlineDesignFont',
		dv: '500 <tabsTitleFont>',
		cp: 'font',
		sel: '.comp.compTabs._underLine > .tabsContainer > .tabDiv',
		np: true,
	},
];
export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
