import { StyleGroupDefinition, StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{ dn: 'Text Font', n: 'textFont', dv: '<primaryFont>' },

	{
		gn: 'SPAN',
		dn: 'SPAN Font',
		n: 'spanTextFont',
		dv: '<primaryFont>',
		cp: 'font',
		sel: '.comp.compText.span',
		np: true,
	},
	{
		gn: 'H1',
		dn: 'H1 Font',
		n: 'h1TextFont',
		dv: 'bold <quinaryFont>',
		cp: 'font',
		sel: '.comp.compText.h1',
		np: true,
	},
	{
		gn: 'H2',
		dn: 'H2 Font',
		n: 'h2TextFont',
		dv: '<quinaryFont>',
		cp: 'font',
		sel: '.comp.compText.h2',
		np: true,
	},
	{
		gn: 'H3',
		dn: 'H3 Font',
		n: 'h3TextFont',
		dv: 'bold <secondaryFont>',
		cp: 'font',
		sel: '.comp.compText.h3',
		np: true,
	},
	{
		gn: 'H4',
		dn: 'H4 Font',
		n: 'h4TextFont',
		dv: '<secondaryFont>',
		cp: 'font',
		sel: '.comp.compText.h4',
		np: true,
	},
	{
		gn: 'H5',
		dn: 'H5 Font',
		n: 'h5TextFont',
		dv: 'bold <tertiaryFont>',
		cp: 'font',
		sel: '.comp.compText.h5',
		np: true,
	},
	{
		gn: 'H6',
		dn: 'H6 Font',
		n: 'h6TextFont',
		dv: '<tertiaryFont>',
		cp: 'font',
		sel: '.comp.compText.h6',
		np: true,
	},
	{
		gn: 'I',
		dn: 'I Font',
		n: 'iTextFont',
		dv: 'italic <primaryFont>',
		cp: 'font',
		sel: '.comp.compText.i i',
		np: true,
	},
	{
		gn: 'P',
		dn: 'P Font',
		n: 'pTextFont',
		dv: '<primaryFont>',
		cp: 'font',
		sel: '.comp.compText.p',
		np: true,
	},
	{
		gn: 'B',
		dn: 'B Font',
		n: 'bTextFont',
		dv: 'bold <primaryFont>',
		cp: 'font',
		sel: '.comp.compText.b',
		np: true,
	},
	{
		gn: 'PRE',
		dn: 'PRE Font',
		n: 'preTextFont',
		dv: '<primaryFont>',
		cp: 'font',
		sel: '.comp.compText.pre',
		np: true,
	},

	{
		gn: 'SPAN',
		dn: 'SPAN Padding',
		n: 'spanTextPadding',
		dv: '0',
		cp: 'padding',
		sel: '.comp.compText.span span',
		np: true,
	},
	{
		gn: 'H1',
		dn: 'H1 Padding',
		n: 'h1TextPadding',
		dv: '5px 0px',
		cp: 'padding',
		sel: '.comp.compText.h1 h1',
		np: true,
	},
	{
		gn: 'H2',
		dn: 'H2 Padding',
		n: 'h2TextPadding',
		dv: '4px 0px',
		cp: 'padding',
		sel: '.comp.compText.h2 h2',
		np: true,
	},
	{
		gn: 'H3',
		dn: 'H3 Padding',
		n: 'h3TextPadding',
		dv: '3px 0px',
		cp: 'padding',
		sel: '.comp.compText.h3 h3',
		np: true,
	},
	{
		gn: 'H4',
		dn: 'H4 Padding',
		n: 'h4TextPadding',
		dv: '2px 0px',
		cp: 'padding',
		sel: '.comp.compText.h4 h4',
		np: true,
	},
	{
		gn: 'H5',
		dn: 'H5 Padding',
		n: 'h5TextPadding',
		dv: '1px 0px',
		cp: 'padding',
		sel: '.comp.compText.h5 h5',
		np: true,
	},
	{
		gn: 'H6',
		dn: 'H6 Padding',
		n: 'h6TextPadding',
		dv: '1px 0px',
		cp: 'padding',
		sel: '.comp.compText.h6 h6',
		np: true,
	},
	{
		gn: 'I',
		dn: 'I Padding',
		n: 'iTextPadding',
		dv: '0',
		cp: 'padding',
		sel: '.comp.compText.i i',
		np: true,
	},
	{
		gn: 'P',
		dn: 'P Padding',
		n: 'pTextPadding',
		dv: '0',
		cp: 'padding',
		sel: '.comp.compText.p p',
		np: true,
	},
	{
		gn: 'B',
		dn: 'B Padding',
		n: 'bTextPadding',
		dv: '0',
		cp: 'padding',
		sel: '.comp.compText.b b',
		np: true,
	},
	{
		gn: 'PRE',
		dn: 'PRE Padding',
		n: 'preTextPadding',
		dv: '0',
		cp: 'padding',
		sel: '.comp.compText.pre pre',
		np: true,
	},

	{
		gn: 'SPAN',
		dn: 'SPAN Margin',
		n: 'spanTextMargin',
		dv: '0',
		cp: 'margin',
		sel: '.comp.compText.span span',
		np: true,
	},
	{
		gn: 'H1',
		dn: 'H1 Margin',
		n: 'h1TextMargin',
		dv: '5px 0px',
		cp: 'margin',
		sel: '.comp.compText.h1 h1',
		np: true,
	},
	{
		gn: 'H2',
		dn: 'H2 Margin',
		n: 'h2TextMargin',
		dv: '4px 0px',
		cp: 'margin',
		sel: '.comp.compText.h2 h2',
		np: true,
	},
	{
		gn: 'H3',
		dn: 'H3 Margin',
		n: 'h3TextMargin',
		dv: '3px 0px',
		cp: 'margin',
		sel: '.comp.compText.h3 h3',
		np: true,
	},
	{
		gn: 'H4',
		dn: 'H4 Margin',
		n: 'h4TextMargin',
		dv: '2px 0px',
		cp: 'margin',
		sel: '.comp.compText.h4 h4',
		np: true,
	},
	{
		gn: 'H5',
		dn: 'H5 Margin',
		n: 'h5TextMargin',
		dv: '1px 0px',
		cp: 'margin',
		sel: '.comp.compText.h5 h5',
		np: true,
	},
	{
		gn: 'H6',
		dn: 'H6 Margin',
		n: 'h6TextMargin',
		dv: '1px 0px',
		cp: 'margin',
		sel: '.comp.compText.h6 h6',
		np: true,
	},
	{
		gn: 'I',
		dn: 'I Margin',
		n: 'iTextMargin',
		dv: '0',
		cp: 'margin',
		sel: '.comp.compText.i i',
		np: true,
	},
	{
		gn: 'P',
		dn: 'P Margin',
		n: 'pTextMargin',
		dv: '0',
		cp: 'margin',
		sel: '.comp.compText.p p',
		np: true,
	},
	{
		gn: 'B',
		dn: 'B Margin',
		n: 'bTextMargin',
		dv: '0',
		cp: 'margin',
		sel: '.comp.compText.b b',
		np: true,
	},
	{
		gn: 'PRE',
		dn: 'PRE Margin',
		n: 'preTextMargin',
		dv: '0',
		cp: 'margin',
		sel: '.comp.compText.pre pre',
		np: true,
	},

	{
		gn: 'SPAN',
		dn: 'SPAN Text Decoration',
		n: 'spanTextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.span span',
		np: true,
	},
	{
		gn: 'H1',
		dn: 'H1 Text Decoration',
		n: 'h1TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h1 h1',
		np: true,
	},
	{
		gn: 'H2',
		dn: 'H2 Text Decoration',
		n: 'h2TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h2 h2',
		np: true,
	},
	{
		gn: 'H3',
		dn: 'H3 Text Decoration',
		n: 'h3TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h3 h3',
		np: true,
	},
	{
		gn: 'H4',
		dn: 'H4 Text Decoration',
		n: 'h4TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h4 h4',
		np: true,
	},
	{
		gn: 'H5',
		dn: 'H5 Text Decoration',
		n: 'h5TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h5 h5',
		np: true,
	},
	{
		gn: 'H6',
		dn: 'H6 Text Decoration',
		n: 'h6TextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.h6 h6',
		np: true,
	},
	{
		gn: 'I',
		dn: 'I Text Decoration',
		n: 'iTextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.i i',
		np: true,
	},
	{
		gn: 'P',
		dn: 'P Text Decoration',
		n: 'pTextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.p p',
		np: true,
	},
	{
		gn: 'B',
		dn: 'B Text Decoration',
		n: 'bTextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.b b',
		np: true,
	},
	{
		gn: 'PRE',
		dn: 'PRE Text Decoration',
		n: 'preTextDecoration',
		cp: 'text-decoration',
		sel: '.comp.compText.pre pre',
		np: true,
	},

	{
		gn: 'Text Component Color',
		dn: 'primaryText',
		n: 'textComponentprimaryTextcolor',
		dv: '<fontColorOne>',
		cp: 'color',
		sel: '.comp.compText._primaryText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'subText',
		n: 'textComponentsubTextcolor',
		dv: '<fontColorTwo>',
		cp: 'color',
		sel: '.comp.compText._subText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'labelText',
		n: 'textComponentlabelTextcolor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compText._labelText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'paragraphText',
		n: 'textComponentparagraphTextcolor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compText._paragraphText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'lightPrimaryText',
		n: 'textComponentlightPrimaryTextcolor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compText._lightPrimaryText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'lightSubText',
		n: 'textComponentlightSubTextcolor',
		dv: '<fontColorSix>',
		cp: 'color',
		sel: '.comp.compText._lightSubText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'lightLabelText',
		n: 'textComponentlightLabelTextcolor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compText._lightLabelText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'lightParagraphText',
		n: 'textComponentlightParagraphTextcolor',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compText._lightParagraphText',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'coloredText1',
		n: 'textComponentcoloredText1color',
		dv: '<colorFifteen>',
		cp: 'color',
		sel: '.comp.compText._coloredText1',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'coloredText2',
		n: 'textComponentcoloredText2color',
		dv: '<colorTen>',
		cp: 'color',
		sel: '.comp.compText._coloredText2',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'coloredText3',
		n: 'textComponentcoloredText3color',
		dv: '<colorEleven>',
		cp: 'color',
		sel: '.comp.compText._coloredText3',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'coloredText4',
		n: 'textComponentcoloredText4color',
		dv: '<colorFourteen>',
		cp: 'color',
		sel: '.comp.compText._coloredText4',
		np: true,
	},
	{
		gn: 'Text Component Color',
		dn: 'coloredText5',
		n: 'textComponentcoloredText5',
		dv: '<colorTwelve>',
		cp: 'color',
		sel: '.comp.compText._coloredText5',
		np: true,
	},

	{
		gn: 'MD Heading1 Font',
		dn: 'MD Heading1 Font Default Design',
		n: 'mDHeading1FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h1',
		np: true,
	},
	{
		gn: 'MD Heading2 Font',
		dn: 'MD Heading2 Font Default Design',
		n: 'mDHeading2FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h2',
		np: true,
	},
	{
		gn: 'MD Heading3 Font',
		dn: 'MD Heading3 Font Default Design',
		n: 'mDHeading3FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h3',
		np: true,
	},
	{
		gn: 'MD Heading4 Font',
		dn: 'MD Heading4 Font Default Design',
		n: 'mDHeading4FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h4',
		np: true,
	},
	{
		gn: 'MD Heading5 Font',
		dn: 'MD Heading5 Font Default Design',
		n: 'mDHeading5FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h5',
		np: true,
	},
	{
		gn: 'MD Heading6 Font',
		dn: 'MD Heading6 Font Default Design',
		n: 'mDHeading6FontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._h6',
		np: true,
	},
	{
		gn: 'MD Paragraph Font',
		dn: 'MD Paragraph Font Default Design',
		n: 'mDParagraphFontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._p',
		np: true,
	},
	{
		gn: 'MD Link Font',
		dn: 'MD Link Font Default Design',
		n: 'mDLinkFontDefaultDesign',
		cp: 'font',
		sel: '.comp.compText._textMarkdown ._markdown ._a',
		np: true,
	},

	{
		gn: 'MD Heading1 Padding',
		dn: 'MD Heading1 Padding Default Design',
		n: 'mDHeading1PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h1',
		np: true,
	},
	{
		gn: 'MD Heading2 Padding',
		dn: 'MD Heading2 Padding Default Design',
		n: 'mDHeading2PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h2',
		np: true,
	},
	{
		gn: 'MD Heading3 Padding',
		dn: 'MD Heading3 Padding Default Design',
		n: 'mDHeading3PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h3',
		np: true,
	},
	{
		gn: 'MD Heading4 Padding',
		dn: 'MD Heading4 Padding Default Design',
		n: 'mDHeading4PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h4',
		np: true,
	},
	{
		gn: 'MD Heading5 Padding',
		dn: 'MD Heading5 Padding Default Design',
		n: 'mDHeading5PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h5',
		np: true,
	},
	{
		gn: 'MD Heading6 Padding',
		dn: 'MD Heading6 Padding Default Design',
		n: 'mDHeading6PaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._h6',
		np: true,
	},
	{
		gn: 'MD Paragraph Padding',
		dn: 'MD Paragraph Padding Default Design',
		n: 'mDParagraphPaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._p',
		np: true,
	},
	{
		gn: 'MD Link Padding',
		dn: 'MD Link Padding Default Design',
		n: 'mDLinkPaddingDefaultDesign',
		cp: 'padding',
		sel: '.comp.compText._textMarkdown ._markdown ._a',
		np: true,
	},

	{
		gn: 'MD Heading1 Margin',
		dn: 'MD Heading1 Margin Default Design',
		n: 'mDHeading1MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h1',
		np: true,
	},
	{
		gn: 'MD Heading2 Margin',
		dn: 'MD Heading2 Margin Default Design',
		n: 'mDHeading2MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h2',
		np: true,
	},
	{
		gn: 'MD Heading3 Margin',
		dn: 'MD Heading3 Margin Default Design',
		n: 'mDHeading3MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h3',
		np: true,
	},
	{
		gn: 'MD Heading4 Margin',
		dn: 'MD Heading4 Margin Default Design',
		n: 'mDHeading4MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h4',
		np: true,
	},
	{
		gn: 'MD Heading5 Margin',
		dn: 'MD Heading5 Margin Default Design',
		n: 'mDHeading5MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h5',
		np: true,
	},
	{
		gn: 'MD Heading6 Margin',
		dn: 'MD Heading6 Margin Default Design',
		n: 'mDHeading6MarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._h6',
		np: true,
	},
	{
		gn: 'MD Paragraph Margin',
		dn: 'MD Paragraph Margin Default Design',
		n: 'mDParagraphMarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._p',
		np: true,
	},
	{
		gn: 'MD Link Margin',
		dn: 'MD Link Margin Default Design',
		n: 'mDLinkMarginDefaultDesign',
		cp: 'margin',
		sel: '.comp.compText._textMarkdown ._markdown ._a',
		np: true,
	},

	{
		gn: 'MD Heading1 Text Decoration',
		dn: 'MD Heading1 Text Decoration Default Design',
		n: 'mDHeading1TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h1',
		np: true,
	},
	{
		gn: 'MD Heading2 Text Decoration',
		dn: 'MD Heading2 Text Decoration Default Design',
		n: 'mDHeading2TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h2',
		np: true,
	},
	{
		gn: 'MD Heading3 Text Decoration',
		dn: 'MD Heading3 Text Decoration Default Design',
		n: 'mDHeading3TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h3',
		np: true,
	},
	{
		gn: 'MD Heading4 Text Decoration',
		dn: 'MD Heading4 Text Decoration Default Design',
		n: 'mDHeading4TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h4',
		np: true,
	},
	{
		gn: 'MD Heading5 Text Decoration',
		dn: 'MD Heading5 Text Decoration Default Design',
		n: 'mDHeading5TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h5',
		np: true,
	},
	{
		gn: 'MD Heading6 Text Decoration',
		dn: 'MD Heading6 Text Decoration Default Design',
		n: 'mDHeading6TextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._h6',
		np: true,
	},
	{
		gn: 'MD Paragraph Text Decoration',
		dn: 'MD Paragraph Text Decoration Default Design',
		n: 'mDParagraphTextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._p',
		np: true,
	},
	{
		gn: 'MD Link Text Decoration',
		dn: 'MD Link Text Decoration Default Design',
		n: 'mDLinkTextDecorationDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._a',
		np: true,
	},

	{
		gn: 'MD Heading1 Color',
		dn: 'MD Heading1 Color Default Design',
		n: 'mDHeading1ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h1',
		np: true,
	},
	{
		gn: 'MD Heading2 Color',
		dn: 'MD Heading2 Color Default Design',
		n: 'mDHeading2ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h2',
		np: true,
	},
	{
		gn: 'MD Heading3 Color',
		dn: 'MD Heading3 Color Default Design',
		n: 'mDHeading3ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h3',
		np: true,
	},
	{
		gn: 'MD Heading4 Color',
		dn: 'MD Heading4 Color Default Design',
		n: 'mDHeading4ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h4',
		np: true,
	},
	{
		gn: 'MD Heading5 Color',
		dn: 'MD Heading5 Color Default Design',
		n: 'mDHeading5ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h5',
		np: true,
	},
	{
		gn: 'MD Heading6 Color',
		dn: 'MD Heading6 Color Default Design',
		n: 'mDHeading6ColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._h6',
		np: true,
	},
	{
		gn: 'MD Paragraph Color',
		dn: 'MD Paragraph Color Default Design',
		n: 'mDParagraphColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._p',
		np: true,
	},
	{
		gn: 'MD Link Color',
		dn: 'MD Link Color Default Design',
		n: 'mDLinkColorDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._a',
		np: true,
	},
	{
		gn: 'MD Link Color On Visited',
		dn: 'MD Link Color On Visited Default Design',
		n: 'mDLinkColorOnVisitedDefaultDesign',
		cp: 'color',
		sel: '.comp.compText._textMarkdown ._markdown ._a:visited',
		np: true,
	},
	{
		gn: 'MD Link Decoration Color ',
		dn: 'MD Link Decoration Color  Default Design',
		n: 'mDLinkDecorationColorDefaultDesign',
		cp: 'text-decoration-color',
		sel: '.comp.compText._textMarkdown ._markdown ._a:visited',
		np: true,
	},
	{
		gn: 'MD Link Color On Hover',
		dn: 'MD Link Color On Hover Default Design',
		n: 'mDLinkColorOnHoverDefaultDesign',
		cp: 'text-decoration',
		sel: '.comp.compText._textMarkdown ._markdown ._a:hover',
		np: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
