import { StylePropertyDefinition } from '../../types/common';

export const styleProperties: Array<StylePropertyDefinition> = [
	{
		dn: 'Checkbox Font',
		n: 'checkboxFont',
		dv: '<primaryFont>',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Checkbox Font',
		n: 'defaultCheckboxFont',
		dv: '<checkboxFont>',
		cp: 'font',
		sel: '.comp.compCheckbox._default label',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Checkbox Font',
		n: 'outlineCheckboxFont',
		dv: '<checkboxFont>',
		cp: 'font',
		sel: '.comp.compCheckbox._outlined label',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Checkbox Font',
		n: 'filledCheckboxFont',
		dv: '<checkboxFont>',
		cp: 'font',
		sel: '.comp.compCheckbox._filled label',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Checkbox Border',
		n: 'defaultCheckboxBorder',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compCheckbox._default .commonCheckbox',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Checkbox Border',
		n: 'outlineCheckboxBorder',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compCheckbox._outlined .commonCheckbox',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Checkbox Border',
		n: 'filledCheckboxBorder',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compCheckbox._filled .commonCheckbox',
		np: true,
	},

	{
		gn: 'Default',
		dn: 'Default Checkbox Border Checked',
		n: 'defaultCheckboxBorderChecked',
		dv: 'none',
		cp: 'border',
		sel: '.comp.compCheckbox._default .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Outline',
		dn: 'Outline Checkbox Border Checked',
		n: 'outlineCheckboxBorderChecked',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compCheckbox._outlined .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Filled',
		dn: 'Filled Checkbox Border Checked',
		n: 'filledCheckboxBorderChecked',
		dv: '2px solid',
		cp: 'border',
		sel: '.comp.compCheckbox._filled .commonCheckbox._checked',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Primary Outline Checkbox Border Color',
		n: 'primaryOutlineCheckboxBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._primary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Secondary Outline Checkbox Border Color',
		n: 'secondaryOutlineCheckboxBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._secondary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Tertiary Outline Checkbox Border Color',
		n: 'tertiaryOutlineCheckboxBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._tertiary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quaternary Outline Checkbox Border Color',
		n: 'quaternaryOutlineCheckboxBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._quaternary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quinary Outline Checkbox Border Color',
		n: 'quinaryOutlineCheckboxBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._quinary .commonCheckbox',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Primary Filled Checkbox Border Color',
		n: 'primaryFilledCheckboxBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._primary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Secondary Filled Checkbox Border Color',
		n: 'secondaryFilledCheckboxBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._secondary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Tertiary Filled Checkbox Border Color',
		n: 'tertiaryFilledCheckboxBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._tertiary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quaternary Filled Checkbox Border Color',
		n: 'quaternaryFilledCheckboxBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._quaternary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quinary Filled Checkbox Border Color',
		n: 'quinaryFilledCheckboxBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._quinary .commonCheckbox',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Primary Outline Checked Checkbox Border Color',
		n: 'primaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._primary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Secondary Outline Checked Checkbox Border Color',
		n: 'secondaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._secondary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Tertiary Outline Checked Checkbox Border Color',
		n: 'tertiaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._tertiary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quaternary Outline Checked Checkbox Border Color',
		n: 'quaternaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._quaternary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quinary Outline Checked Checkbox Border Color',
		n: 'quinaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._quinary .commonCheckbox._checked',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Primary Outline Checked Checkbox Border Color',
		n: 'primaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorThree>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._primary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Secondary Outline Checked Checkbox Border Color',
		n: 'secondaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorFour>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._secondary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Tertiary Outline Checked Checkbox Border Color',
		n: 'tertiaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorFive>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._tertiary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quaternary Outline Checked Checkbox Border Color',
		n: 'quaternaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorNine>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._quaternary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Border Color',
		dn: 'Quinary Outline Checked Checkbox Border Color',
		n: 'quinaryOutlineCheckedCheckboxBorderColor',
		dv: '<fontColorSeven>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._filled._quinary .commonCheckbox._checked',
		np: true,
	},

	{
		gn: 'Background Color',
		dn: 'Primary Default Checkbox Background',
		n: 'primaryDefaultCheckboxBackground',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._primary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Secondary Default Checkbox Background',
		n: 'secondaryDefaultCheckboxBackground',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._secondary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Tertiary Default Checkbox Background',
		n: 'tertiaryDefaultCheckboxBackground',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._tertiary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Quaternary Default Checkbox Background',
		n: 'quaternaryDefaultCheckboxBackground',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._quaternary .commonCheckbox',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Quinary Default Checkbox Background',
		n: 'quinaryDefaultCheckboxBackground',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._quinary .commonCheckbox',
		np: true,
	},

	{
		gn: 'Background Color',
		dn: 'Outline Checkbox Background',
		n: 'outlineCheckboxBackground',
		dv: '<backgroundColorSeven>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined .commonCheckbox',
		np: true,
	},

	{
		gn: 'Background Color',
		dn: 'Primary Filled Checkbox Background',
		n: 'primaryFilledCheckboxBackground',
		dv: '<backgroundColorOne>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled._primary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Secondary Filled Checkbox Background',
		n: 'secondaryFilledCheckboxBackground',
		dv: '<backgroundColorTwo>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled._secondary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Tertiary Filled Checkbox Background',
		n: 'tertiaryFilledCheckboxBackground',
		dv: '<backgroundColorThree>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled._tertiary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Quaternary Filled Checkbox Background',
		n: 'quaternaryFilledCheckboxBackground',
		dv: '<backgroundColorFour>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled._quaternary .commonCheckbox._checked',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Quinary Filled Checkbox Background',
		n: 'quinaryFilledCheckboxBackground',
		dv: '<backgroundColorFive>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled._quinary .commonCheckbox._checked',
		np: true,
	},

	{
		gn: 'Tick Color',
		dn: 'Checkbox Tick Color',
		n: 'checkboxTickColor',
		dv: '<backgroundColorSeven>',
		cp: 'background',
		sel: '.comp.compCheckbox._default .commonCheckbox ._thumb',
		np: true,
	},

	{
		gn: 'Tick Color',
		dn: 'Filled Tick Color',
		n: 'filledTickColor',
		dv: '<backgroundColorSeven>',
		cp: 'background',
		sel: '.comp.compCheckbox._filled .commonCheckbox ._thumb',
		np: true,
	},

	{
		gn: 'Tick Color',
		dn: 'Primary Outline Checkbox Tick Color',
		n: 'primaryOutlineCheckboxTickColor',
		dv: '<fontColorThree>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._primary .commonCheckbox ._thumb',
		np: true,
	},
	{
		gn: 'Tick Color',
		dn: 'Secondary Outline Checkbox Tick Color',
		n: 'secondaryOutlineCheckboxTickColor',
		dv: '<fontColorFour>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._secondary .commonCheckbox ._thumb',
		np: true,
	},
	{
		gn: 'Tick Color',
		dn: 'Tertiary Outline Checkbox Tick Color',
		n: 'tertiaryOutlineCheckboxTickColor',
		dv: '<fontColorFive>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._tertiary .commonCheckbox ._thumb',
		np: true,
	},
	{
		gn: 'Tick Color',
		dn: 'Quaternary Outline Checkbox Tick Color',
		n: 'quaternaryOutlineCheckboxTickColor',
		dv: '<fontColorNine>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._quaternary .commonCheckbox ._thumb',
		np: true,
	},
	{
		gn: 'Tick Color',
		dn: 'Quinary Outline Checkbox Tick Color',
		n: 'quinaryOutlineCheckboxTickColor',
		dv: '<fontColorSeven>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._quinary .commonCheckbox ._thumb',
		np: true,
	},

	{
		gn: 'Border Color',
		dn: 'Outline Disabled Checkbox Border Color',
		n: 'outlineDisabledCheckboxBorderColor',
		dv: '<fontColorEight>',
		cp: 'border-color',
		sel: '.comp.compCheckbox._outlined._primary .commonCheckbox._disabled,.comp.compCheckbox._outlined._secondary .commonCheckbox._disabled,.comp.compCheckbox._outlined._tertiary .commonCheckbox._disabled,.comp.compCheckbox._outlined._quaternary .commonCheckbox._disabled,.comp.compCheckbox._outlined._quinary .commonCheckbox._disabled',
		np: true,
	},
	{
		gn: 'Background Color',
		dn: 'Default Disabled Checkbox Background',
		n: 'defaultDisabledCheckboxBackground',
		dv: '<backgroundColorEight>',
		cp: 'background',
		sel: '.comp.compCheckbox._default._primary .commonCheckbox._disabled,.comp.compCheckbox._default._secondary .commonCheckbox._disabled,.comp.compCheckbox._default._tertiary .commonCheckbox._disabled,.comp.compCheckbox._default._quaternary .commonCheckbox._disabled,.comp.compCheckbox._default._quinary .commonCheckbox._disabled',
		np: true,
	},
	{
		gn: 'Tick Color',
		dn: ' Outline Disabled Checkbox Tick Color',
		n: ' OutlineDisabledCheckboxTickColor',
		dv: '<fontColorEight>',
		cp: 'background',
		sel: '.comp.compCheckbox._outlined._primary .commonCheckbox._disabled ._thumb,.comp.compCheckbox._outlined._secondary .commonCheckbox._disabled ._thumb,.comp.compCheckbox._outlined._tertiary .commonCheckbox._disabled ._thumb,.comp.compCheckbox._outlined._quaternary .commonCheckbox._disabled ._thumb,.comp.compCheckbox._outlined._quinary .commonCheckbox._disabled ._thumb',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Outline Disabled Checkbox Font Color',
		n: 'outlineDisabledCheckboxFontColor',
		dv: '<fontColorEight>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined label._disabled',
		np: true,
	},

	{
		gn: 'Font Color',
		dn: 'Primary Outline Checkbox Font Color',
		n: 'primaryOutlineCheckboxFontColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined._primary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Secondary Outline Checkbox Font Color',
		n: 'secondaryOutlineCheckboxFontColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined._secondary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Tertiary Outline Checkbox Font Color',
		n: 'tertiaryOutlineCheckboxFontColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined._tertiary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Quaternary Outline Checkbox Font Color',
		n: 'quaternaryOutlineCheckboxFontColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined._quaternary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Quinary Outline Checkbox Font Color',
		n: 'quinaryOutlineCheckboxFontColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compCheckbox._outlined._quinary',
		np: true,
	},

	{
		gn: 'Font Color',
		dn: 'Primary Filled Checkbox Font Color',
		n: 'primaryFilledCheckboxFontColor',
		dv: '<fontColorThree>',
		cp: 'color',
		sel: '.comp.compCheckbox._filled._primary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Secondary Filled Checkbox Font Color',
		n: 'secondaryFilledCheckboxFontColor',
		dv: '<fontColorFour>',
		cp: 'color',
		sel: '.comp.compCheckbox._filled._secondary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Tertiary Filled Checkbox Font Color',
		n: 'tertiaryFilledCheckboxFontColor',
		dv: '<fontColorFive>',
		cp: 'color',
		sel: '.comp.compCheckbox._filled._tertiary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Quaternary Filled Checkbox Font Color',
		n: 'quaternaryFilledCheckboxFontColor',
		dv: '<fontColorNine>',
		cp: 'color',
		sel: '.comp.compCheckbox._filled._quaternary',
		np: true,
	},
	{
		gn: 'Font Color',
		dn: 'Quinary Filled Checkbox Font Color',
		n: 'quinaryFilledCheckboxFontColor',
		dv: '<fontColorSeven>',
		cp: 'color',
		sel: '.comp.compCheckbox._filled._quinary',
		np: true,
	},
];

export const styleDefaults = new Map<string, string>(
	styleProperties
		.filter(e => !!e.dv)
		.map(({ n: name, dv: defaultValue }) => [name, defaultValue!]),
);
